# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5017758cb54bc82e43ede41c02a7ce4dcd629013c2b605f33cfb66d926bce23fb53d004f7ad7b82e582750f250b08714de6599dd5a7bd177b9fafb777f0515b2

test:
  secret_key_base: df69c8af6e6f55f458907d56ee0b61cf1f5f2bb431077184230ddc23aab4ecb0ff1bfe583ff9dcd3de788b88ffc3003526884f127f7ef09783271974dc4bcaed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
